name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('api/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: fmt
        run: cargo fmt -- --check
      - name: lint
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
